from snakemake.utils import min_version

min_version('8.11')


configfile: 'config/data.json'
configfile: 'config/my_data.json'
configfile: 'config/params.json'


module widevariant:
    snakefile: github('fm-key-lab/widevariant_module', path='workflow/Snakefile', tag='0.0.4-alpha')
    config: config


include: 'rules/samplesheet.smk'
include: 'rules/mapping.smk'
include: 'rules/sequence_typing.smk'
include: 'rules/phylogeny.smk'
include: 'rules/prepare_results.smk'
include: 'rules/prepare_report.smk'


rule all:
    input:
        'report/main.pdf',
        expand(
            'results/{species}/phylogeny.done',
            species=config['wildcards']['species_tmp'].split('|')
        )
    localrule: True
    default_target: True


onstart:
    shell('mkdir -p logs results')
    shell('find logs -type f ! -path "logs/notebooks/*" -delete')
    shell('rm -f .nextflow.log*')


onsuccess:
    shell(f'mkdir -p "/r/t/thosi/{config['run_id']}"')

    # TODO: Should specify what's tranferred (e.g., leave `results/../work` from nf behind).
    shell(f'rsync -au --progress report "/r/t/thosi/{config['run_id']}/"')
    shell(f'rsync -au --progress --exclude "work" results "/r/t/thosi/{config['run_id']}/"')
    
    # Clean up compiled report
    shell('rm -f report/main.pdf')