executor: slurm
jobs: 200
latency-wait: 5
slurm-init-seconds-before-status-checks: 5

benchmark-extended: true
keep-going: false
printshellcmds: false

software-deployment-method: env-modules
apptainer-args: "--bind '/tmp' --bind '/u/thosi/dev/projects' --bind '/u/thosi/dev/datasets' --bind '/ptmp/thosi' --bind '/raven/ptmp/thosi'"

default-resources:
    slurm_account: "mib_cpu"
    slurm_partition: "general,small"
    slurm_extra: "'-o ./logs/slurm_%x_%j.out -e ./logs/slurm_%x_%j.err --exclude=raven[03-06]'"
    jobname: "'slurm_%x_%j'"
    mem_mb: 512
    runtime: 30 # minutes